In [1]:
!pip3 install torch

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.8/55.8 MB 2.4 MB/s eta 0:00:00m eta 0:00:010:00:01m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.1/133.1 kB 3.6 MB/s eta 0:00:00 MB/s eta 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 3.2 MB/s eta 0:00:00m eta 0:00:010:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 2.5 MB/s eta 0:00:002.5 MB/s eta 0:00:010m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 2.1 MB/s eta 0:00:00 MB/s eta 0:00:01:01

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python3.10 -m pip install --upgrade pip


In [2]:

import torch
import numpy as np

# Tensor Initialization
### multiple ways
### 1 - using data
data = [
[1,2],
[3,4]
]
x_data = torch.tensor(data)
print(type(x_data))
### 2 - using numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)
print(type(x_np))
### 3 - using another tensor
x_ones = torch.ones_like(x_data)
print("One Tensor: \n",x_ones)
x_rand = torch.rand_like(x_data,dtype=torch.float)
print(x_rand)
#### more ways to create tensors
shape = (2,3)
random_tensor = torch.rand(shape)
print(random_tensor)
print(type(random_tensor))
ones_tensor = torch.ones(shape)
print(ones_tensor)
print(type(ones_tensor))
zeros_tensor = torch.zeros(shape)
print(zeros_tensor)
print(type(zeros_tensor))
tensor = torch.rand(3,4)
print(tensor)
tensor.shape
tensor.dtype
tensor.device
# Tensor Operations
if torch.cuda.is_available():
 tensor = tensor.to('cuda')
print("Device tensor is stored in ", tensor.device)
# Indexing, Slicing
tensor = torch.ones(4,4)



print(f"tensor : ",tensor)

tensor1 = torch.zeros(4,4)
print(f"tensor1 : ",tensor1)
tensor2 = torch.cat([tensor,tensor1])
print(f"tensor2 : ",tensor2)
# Multiply Operation
tensor.mul(tensor1)
tensor * tensor1
tensor.T
# inplace - change the original tensor
tensor.add_(3)
print(tensor)
# from tensor to numpy
t = torch.ones(5)
print(t)
n = t.numpy()
print(n)
print(type(n))

<class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>
One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.2761, 0.1995],
        [0.6807, 0.4049]])
tensor([[0.7232, 0.1461, 0.4460],
        [0.5119, 0.8806, 0.4597]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.8926, 0.1010, 0.7309, 0.9413],
        [0.8534, 0.6270, 0.2662, 0.4339],
        [0.0992, 0.8523, 0.9266, 0.3230]])
Device tensor is stored in  cpu
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0.