# Tensorflow

In [3]:
import numpy as np
import tensorflow as tf 
a=tf.constant(15)
b=tf.constant(20)
print(a+b)

tf.Tensor(35, shape=(), dtype=int32)


In [4]:
x=np.random.rand(100).astype(np.float32)
print(x)

[0.96572423 0.34497866 0.7421628  0.17897393 0.23823911 0.7735159
 0.67752653 0.22286783 0.14112815 0.11118194 0.15020266 0.5419511
 0.38106441 0.2715826  0.91285676 0.16911468 0.85728663 0.6019359
 0.9156174  0.43641478 0.68027425 0.76000667 0.7877019  0.5619625
 0.803183   0.27096313 0.35265404 0.65533084 0.6049436  0.9451219
 0.5846114  0.98555493 0.30043384 0.6747333  0.7790742  0.34337983
 0.04212314 0.23591276 0.17679708 0.48841745 0.69354916 0.01765083
 0.13986777 0.8733419  0.70061177 0.5837639  0.4762527  0.40829223
 0.5016815  0.47364157 0.7576067  0.7994594  0.88537097 0.8876027
 0.44569737 0.7500926  0.66051596 0.8484728  0.16211471 0.6540168
 0.192994   0.4530486  0.13519813 0.5122175  0.9851944  0.43465433
 0.7370678  0.6376797  0.28316924 0.33704066 0.96453166 0.76420593
 0.43593797 0.45172146 0.6309972  0.46034926 0.37453735 0.3517094
 0.86007065 0.8217896  0.6722369  0.2802551  0.65724504 0.34168872
 0.07407109 0.9487521  0.00920665 0.5820032  0.42697185 0.68221545
 0.

In [5]:
y=x*0.2+0.2
W=tf.Variable(tf.random.normal([1]))
b=tf.Variable(tf.zeros([1]))

In [6]:
def mse_loss():
  ypred=W* x+b
  loss=tf.reduce_mean(tf.square(ypred-y))
  return loss

In [7]:
optimizer=tf.keras.optimizers.Adam()
for step in range(5000):
  optimizer.minimize(mse_loss, var_list=[W,b])
  if step % 500 == 0:
    print(step, W.numpy(),b.numpy())

0 [-1.1331582] [0.001]
500 [-0.7290962] [0.39096424]
1000 [-0.51823914] [0.5399393]
1500 [-0.40944546] [0.5366595]
2000 [-0.3154979] [0.4890532]
2500 [-0.21537457] [0.43294856]
3000 [-0.11351237] [0.37574932]
3500 [-0.01790558] [0.32210943]
4000 [0.06365212] [0.27638653]
4500 [0.12547484] [0.24174517]


# Keras

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import pandas as pd

In [9]:
dataset =  pd.read_csv('diabetes.csv', delimiter=',')
dataset

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [10]:
x = dataset.iloc[:,0:8]
print(x.shape)
y = dataset.iloc[:,8]
print(y)

(768, 8)
0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


In [11]:
model = Sequential()

In [12]:
model.add(Dense(12,input_shape=(8,),activation='relu'))

In [13]:
model.add(Dense(8, activation='relu'))

In [14]:
model.add(Dense(1,activation='sigmoid'))

In [15]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
model.fit(x,y, epochs=150, batch_size=10)

Epoch 1/150
77/77 [==============================] - 0s 679us/step - loss: 12.7038 - accuracy: 0.6510
Epoch 2/150
77/77 [==============================] - 0s 645us/step - loss: 2.8632 - accuracy: 0.6211
Epoch 3/150
77/77 [==============================] - 0s 645us/step - loss: 0.9607 - accuracy: 0.5859
Epoch 4/150
77/77 [==============================] - 0s 605us/step - loss: 0.7851 - accuracy: 0.5651
Epoch 5/150
77/77 [==============================] - 0s 618us/step - loss: 0.7017 - accuracy: 0.5924
Epoch 6/150
77/77 [==============================] - 0s 605us/step - loss: 0.6715 - accuracy: 0.6107
Epoch 7/150
77/77 [==============================] - 0s 605us/step - loss: 0.6474 - accuracy: 0.6315
Epoch 8/150
77/77 [==============================] - 0s 592us/step - loss: 0.6395 - accuracy: 0.6471
Epoch 9/150
77/77 [==============================] - 0s 618us/step - loss: 0.6353 - accuracy: 0.6354
Epoch 10/150
77/77 [==============================] - 0s 605us/step - loss: 0.6257 - accur

In [17]:
model.evaluate(x,y)

24/24 [==============================] - 0s 695us/step - loss: 0.5706 - accuracy: 0.6992


[0.5706384181976318, 0.69921875]

# PyTorch

In [2]:
import torch
import numpy as np

In [3]:
#using data
data = [ 
 [1,2], 
 [3,4] 
] 
x_data = torch.tensor(data) 
print(x_data)
print(type(x_data)) 

tensor([[1, 2],
        [3, 4]])
<class 'torch.Tensor'>


In [4]:
#using numpy array 
np_array = np.array(data) 
x_np = torch.from_numpy(np_array) 
print(x_np) 
print(type(x_np))

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
<class 'torch.Tensor'>


In [5]:
#using another tensor 
x_ones = torch.ones_like(x_data) 
print("One Tensor: \n",x_ones) 
x_rand = torch.rand_like(x_data,dtype=torch.float) 
print(x_rand) 

One Tensor: 
 tensor([[1, 1],
        [1, 1]])
tensor([[0.3013, 0.7416],
        [0.3376, 0.0398]])


In [8]:
# more ways to create tensors 
shape = (2,3) 
random_tensor = torch.rand(shape) 
print(random_tensor) 
print(type(random_tensor)) 
ones_tensor = torch.ones(shape) 
print(ones_tensor) 
print(type(ones_tensor)) 
zeros_tensor = torch.zeros(shape) 
print(zeros_tensor) 
print(type(zeros_tensor)) 
tensor = torch.rand(3,4) 
print(tensor) 
print(type(tensor))

tensor([[0.2072, 0.1619, 0.3673],
        [0.3414, 0.1611, 0.1831]])
<class 'torch.Tensor'>
tensor([[1., 1., 1.],
        [1., 1., 1.]])
<class 'torch.Tensor'>
tensor([[0., 0., 0.],
        [0., 0., 0.]])
<class 'torch.Tensor'>
tensor([[0.6838, 0.5278, 0.5237, 0.5776],
        [0.7557, 0.4264, 0.7474, 0.3925],
        [0.3442, 0.9778, 0.1214, 0.7322]])
<class 'torch.Tensor'>


In [10]:
# Indexing, Slicing 
tensor = torch.ones(4,4)
print(tensor) 
print(tensor) 
tensor1 = torch.zeros(4,4) 
print(tensor1) 
tensor2 = torch.cat([tensor,tensor1]) 
print(tensor2) 

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [11]:
# Multiply Operation 
tensor.mul(tensor1) 
tensor * tensor1 
tensor.T

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [9]:
# inplace - change the original tensor 
tensor.add_(3) 
print(tensor) 

tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [10]:
# from tensor to numpy 
t = torch.ones(5) 
print(t) 
n = t.numpy() 
print(n) 
print(type(n)) 

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
